name: Bogazici-DevSecOps-Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest
    name: Build image & security scan

    steps:
      # 1. Kodu çek
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Docker imajını build et
      - name: Build Docker image
        run: |
          docker build -t juice-shop:${{ github.sha }} .

      # 3. Syft ile SBOM çıkar
      - name: Syft SBOM Scan
        uses: anchore/sbom-action@v0
        with:
          image: "juice-shop:${{ github.sha }}"
          output-file: "sbom.spdx.json"
          format: "spdx-json"

      # 4. Semgrep taraması (bulgu olsa bile pipeline kırılmasın)
      - name: Run Semgrep (no fail on findings)
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        with:
          config: "p/default"  # veya "p/security-audit"

      # 5. GitLeaks taraması (gizli anahtar/şifre arar)
      - name: Run GitLeaks (no fail on findings)
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true  # bulgu olsa bile job kırmızıya düşmesin
        with:
          args: detect --source . --no-banner
