name: Build Juice Shop

on:
  push:
    branches: [ master ]
  pull_request:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Juice Shop Node 20 ile uyumlu

      - name: Install dependencies
        run: npm install   # <-- package-lock yoksa bu çalışır

      - name: Build project
        run: npm run build

      # İstersen testleri de çalıştırabilirsin
      - name: Run tests
        run: npm test

      # Build çıktısını artifact olarak yüklemek istersen
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/   # build çıktısının olduğu klasör
