name: Build security.yml    # Workflow’un adı

on:                    # Ne zaman çalışacağını belirler
  push:                # Main brancha push olduğunda çalışsın
    branches: [ master ]
  pull_request:        # PR açıldığında da çalışsın

jobs:                  # Birden fazla job olabilir
  build:               # Build adlı job
    runs-on: ubuntu-latest  # Çalışacağı işletim sistemi (runner)

    steps:             # Bu job içindeki adımlar
      - name: Checkout code
        uses: actions/checkout@v4  # Kodu runner’a indirir

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'       # Kullanılacak Node versiyonu

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build          # Build komutu (Angular/React vs. olabilir)

      - name: Run tests (optional)
        run: npm test               # İstersen test çalıştırabilirsin

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/               # Derleme çıktısının olduğu klasör
