name: Bogazici-DevSecOps-Pipeline

on:
  push:
    branches: 
      - master 
  pull_request:

jobs:
  build-and-sbom:
    name: Build & SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t juice-shop:${{ github.sha }} .

      - name: Syft SBOM Scan
        uses: anchore/sbom-action@v0
        with:
          image: "juice-shop:${{ github.sha }}"
          output-file: "sbom.spdx.json"
          format: "spdx-json"

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/default"
